global:
  parameters: {}
  regions:
    - us-east-1

plans:
  dev:
    parameters:
      DBInstanceClass: db.t2.large
      AllocatedStorageAndIops: "100GB 1000IOPS"
      EngineVersion: "5.7.17"
      MysqlServerTimezone: "UTC"
      PubliclyAccessible: "false"
      AccessCidr: "10.0.0.0/16"
