AWSTemplateFormatVersion: 2010-09-09
Description: "AWS Service Broker - Amazon Polly (qs-1ob09h6a9)"
Metadata:
  'AWS::ServiceBroker::Specification':
    Version: 1.0
    Tags:
      - AWS
      - Polly
      - TTS
      - Speech
    Name: polly
    DisplayName: "Amazon Polly"
    LongDescription: "Amazon Polly is a Text-to-Speech (TTS) cloud service that converts text into lifelike speech. You can use Amazon Polly to develop applications that increase engagement and accessibility. Amazon Polly supports multiple languages and includes a variety of lifelike voices, so you can build speech-enabled applications that work in multiple locations and use the ideal voice for your customers."
    ImageUrl: "https://s3.amazonaws.com/awsservicebroker/icons/AmazonPolly_LARGE.png"
    DocumentationUrl: 'https://aws.amazon.com/documentation/polly/'
    ProviderDisplayName: "Amazon Web Services"
    Bindings:
      IAM:
        AddKeypair: True
        Policies:
          - PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                  - polly:SynthesizeSpeech
                  - polly:DeleteLexicon
                  - polly:GetLexicon
                  - polly:PutLexicon
                  Resource: !Sub "arn:aws:polly:${AWS::Region}:${AWS::AccountId}:lexicon/${LexiconPrefix}*"
                - Effect: Allow
                  Action:
                  - polly:ListLexicons
                  - polly:DescribeVoices
                  Resource: "*"
      CFNOutputs: []
    ServicePlans:
        default:
          DisplayName: "Standard"
          Description: 'AWS Polly'
          LongDescription: "Enables use of AWS Polly Speech Synthesis"
          Cost: "https://aws.amazon.com/polly/pricing/"
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Polly Configuration"
        Parameters:
          - LexiconPrefix
    ParameterLabels:
      LexiconPrefix:
        default: "Lexicon Prefix"
Parameters:
  LexiconPrefix:
    Description: >-
      Restrict the use of Polly lexicons to those with the specified prefix. If left blank all lexicons can be managed.
      The restriction applies to the SynthesizeSpeech, GetLexicon, PutLexicon and DeleteLexicon API's
    Type: String
    Default: ""
Resources: {}
Outputs:
  PollyLexiconPrefix:
    Description: Only lexicons with this prefix are available.
    Value: !Ref LexiconPrefix
