global:
  parameters: {}
  regions:
    - us-east-1

plans:
  production:
    parameters:
      NumberOfNodes: '2'
      NodeType: "dc1.large"
      AccessCidr: "10.0.0.0/16"
      StorageEncrypted: "True"
      PubliclyAccessible: "False"
      UseElasticIP: "False"
      PreferredMaintenanceWindowDay: Mon
      PreferredMaintenanceWindowStartTime: "04:00"
      PreferredMaintenanceWindowEndTime: "06:00"