global:
  parameters: {}
  regions:
    - us-east-1

plans:
  dev:
    parameters:
      DBInstanceClass: db.t2.large
      PostgresServerTimezone: "UTC"
      PubliclyAccessible: "false"
      AccessCidr: "10.0.0.0/16"
