AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Rekognition (qs-1ob09h6ao)
Metadata:
  'AWS::ServiceBroker::Specification':
    Version: 1.0
    Tags:
      - AWS
      - Rekognition
      - Image
    Name: rekognition-apb
    DisplayName: "Amazon Rekognition"
    LongDescription: "Amazon Rekognition makes it easy to add image and video analysis to your applications. You just provide an image or video to the Rekognition API, and the service can identify the objects, people, text, scenes, and activities, as well as detect any inappropriate content. Amazon Rekognition also provides highly accurate facial analysis and facial recognition. You can detect, analyze, and compare faces for a wide variety of user verification, cataloging, people counting, and public safety use cases."
    ImageUrl: "https://s3.amazonaws.com/awsservicebroker/icons/AmazonRekognition_LARGE.png"
    DocumentationUrl: 'https://aws.amazon.com/documentation/rekognition/'
    ProviderDisplayName: "Amazon Web Services"
    Bindings:
      IAM:
        AddKeypair: True
        Policies:
          - PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                  - "rekognition:DetectLabels"
                  - "rekognition:ListCollections"
                  - "rekognition:DetectFaces"
                  - "rekognition:DetectModerationLabels"
                  - "rekognition:IndexFaces"
                  - "rekognition:RecognizeCelebrities"
                  - "rekognition:CompareFaces"
                  - "rekognition:DetectText"
                  - "rekognition:GetCelebrityInfo"
                  - "rekognition:ListFaces"
                  - "rekognition:CreateCollection"
                  - "rekognition:SearchFaces"
                  - "rekognition:DeleteCollection"
                  - "rekognition:DeleteFaces"
                  - "rekognition:SearchFacesByImage"
                  Resource: "*"
      CFNOutputs: []
    ServicePlans:
        default:
          DisplayName: "Image"
          Description: 'AWS Rekognition Image'
          LongDescription: "Enables use of AWS Rekognition Image api's"
          Cost: "https://aws.amazon.com/rekognition/pricing/"
Resources: {}
