AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS Service Broker - Amazon DynamoDB (qs-1nt0fs927)'
Metadata:
  'AWS::ServiceBroker::Specification':
    Version: 1.0
    Tags:
      - AWS
      - RDS
      - DynamoDB
      - database
      - NoSQL
    Name: dynamodb
    DisplayName: "Amazon DynamoDB"
    LongDescription: >-
      Amazon DynamoDB is a fully managed NoSQL database service that provides fast and
      predictable performance with seamless scalability. You can use Amazon DynamoDB to
      create a database table that can store and retrieve any amount of data, and serve
      any level of request traffic. Amazon DynamoDB automatically spreads the data and
      traffic for the table over a sufficient number of servers to handle the request
      capacity specified by the customer and the amount of data stored, while maintaining
      consistent and fast performance.
    ImageUrl: "https://s3.amazonaws.com/thp-aws-icons-dev/Database_AmazonDynamoDB_LARGE.png"
    DocumentationUrl: 'https://aws.amazon.com/documentation/dynamodb/'
    ProviderDisplayName: "Amazon Web Services"
    Bindings:
      IAM:
        AddKeypair: True
        Policies:
          - PolicyDocument:
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "dynamodb:BatchGetItem",
                        "dynamodb:BatchWriteItem",
                        "dynamodb:DeleteItem",
                        "dynamodb:GetItem",
                        "dynamodb:PutItem",
                        "dynamodb:Query",
                        "dynamodb:Scan",
                        "dynamodb:UpdateItem"
                    ],
                    "Effect": "Allow",
                    "Resource": !GetAtt DynamoDBTable.Arn
                }
            ]
          }
      CFNOutputs: [TableName, TableArn]
    ServicePlans:
        hashrange:
          DisplayName: "Hash and Range table"
          Description: 'DynamoDB Table'
          LongDescription: "DynamoDB Table with hash and range keys"
          Cost: "https://aws.amazon.com/dynamodb/pricing/"
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "DynamoDB Settings"
        Parameters:
          - HashAttributeName
          - HashAttributeType
          - RangeAttributeName
          - RangeAttributeType
          - ReadCapacityUnits
          - WriteCapacityUnits
    ParameterLabels:
      HashAttributeName:
        default: "Hash Attribute Name"
      HashAttributeType:
        default: "Hash Attribute Type"
      RangeAttributeName:
        default: "Range Attribute Name"
      RangeAttributeType:
        default: "Range Attribute Type"
      ReadCapacityUnits:
        default: "Read Capacity Units"
      WriteCapacityUnits:
        default: "Write Capacity Units"
Parameters:
  HashAttributeName:
    Type: String
    Description: Name of the Hash key
  HashAttributeType:
    Type: String
    AllowedValues:
      - S
      - N
      - B
    Default: "S"
    Description: AttributeType for  Hash key
  RangeAttributeName:
    Type: String
    Description: Name of the Range key
  RangeAttributeType:
    Type: String
    AllowedValues:
      - S
      - N
      - B
    Default: "S"
    Description: AttributeType for the  Range key
  ReadCapacityUnits:
    Type: String
    Description: Read ReadCapacity Units
    Default: "5"
  WriteCapacityUnits:
    Type: String
    Description: Write Capacity Units
    Default: "5"
Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      KeySchema:
        -
          AttributeName: !Ref HashAttributeName
          KeyType: "HASH"
        -
          AttributeName: !Ref RangeAttributeName
          KeyType: "RANGE"
      AttributeDefinitions:
        -
          AttributeName: !Ref HashAttributeName
          AttributeType: "S"
        -
          AttributeName: !Ref RangeAttributeName
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
Outputs:
  TableName:
    Description: Name of the DynamoDB Table
    Value: !Ref DynamoDBTable
  TableArn:
    Description: Arn of the DynamoDB Table
    Value: !GetAtt DynamoDBTable.Arn
